//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winc_Weather_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherCache
    {
        public int WeatherCacheId { get; set; }
        public int LocationId { get; set; }
        public string Response { get; set; }
        public System.DateTime TimeReceived { get; set; }
    }
}
